"""
One failure shape for every ABDM failure (ADR-012).

`/docs/hiecm/v3/getting-started/build-it-well` says 2 things that shape this module:
  - "Every code in the error code reference carries an action. Key your handling to that column
    rather than to a list of codes you maintain by hand." -> `error_catalogue.ERROR_ACTIONS`,
    generated by `scripts/generate-error-catalogue.py`.
  - "A code on its own is not an error message. Say what failed and what the person can do next."
    -> every `Failure` carries 2 plain sentences.

`classify()` covers a refusal with a code, a refusal without one, an HTTP 5xx, a timeout, a
network error, an error block on a callback, and an answer that never came.

Pure module: no Django import, so `backend/tests` can import it. The desk sentences never say
gateway, callback, care context, HRP, bridge, token or probe (ADR-011).
"""

import re
from dataclasses import dataclass
from datetime import datetime, timedelta

from abdm.error_catalogue import ERROR_ACTIONS

# --- actions -----------------------------------------------------------------------------
# The first 10 are the docs' "What to do" column. The last 3 are the plug's own.

FIX_REQUEST = "fix_request"
FIX_AUTH = "fix_auth"
NEW_REQUEST_ID = "new_request_id"
NEW_CONSENT = "new_consent"
RETRY = "retry"
BACK_OFF = "back_off"
CANNOT_PROCEED = "cannot_proceed"
ASK_SUPPORT = "ask_support"
TREAT_AS_SUCCESS = "treat_as_success"
CHASE_HIP = "chase_hip"
BLOCKED = "blocked"
WAIT = "wait"
UNCLASSIFIED = "unclassified"

# --- retry kinds -------------------------------------------------------------------------

NOW = "now"  # safe to send again at once; the task retries with backoff
AFTER = "after"  # safe to send again only after `retry_after_seconds`
NEVER = "never"  # a repeat cannot help

# --- waits -------------------------------------------------------------------------------

# ABDM-1092. The gateway refuses a second link-token request for the same ABHA address at the
# same HIP inside this window. Observed 2026-09-17: refused up to 362 s, accepted from 374 s
# (findings F6, ADR-012). 7 minutes is the accepted figure plus margin.
TOKEN_REQUEST_WINDOW = timedelta(minutes=7)
# ABDM-1027 names the wait itself: "Please try again after 24 hours."
BLOCK_WAIT = timedelta(hours=24)
# ABDM-1022 "Too many requests". The threshold is not published (`concepts/gateway`), so back off.
BACK_OFF_WAIT = timedelta(minutes=1)
# An answer that never comes. Observed latency 1.9 s (E12); observed delivery retry 16 minutes
# (ADR-012). After this the plug reports "ABDM did not answer".
CALLBACK_DEADLINE = timedelta(minutes=10)

SUPPORT_LINE = "Give this reference to support: {reference}."
ADMIN_LINE = "Tell the administrator."


@dataclass(frozen=True)
class Failure:
    """What happened, what to do, and whether a repeat can help."""

    code: str = ""
    action: str = UNCLASSIFIED
    retry: str = NEVER
    retry_after_seconds: int = 0
    retry_at: datetime | None = None
    what: str = ""
    next_step: str = ""
    detail: str = ""
    support_reference: str = ""
    # The link call says the patient permission is wrong: drop it and ask for a new one.
    renew_permission: bool = False

    @property
    def succeeded(self) -> bool:
        return self.action == TREAT_AS_SUCCESS

    @property
    def retry_now(self) -> bool:
        return self.retry == NOW

    def as_dict(self) -> dict:
        """The `failure` block the state endpoint carries. The desk reads `what` and `nextStep`.
        `detail` holds ABDM's own words and `code` holds the code; both are for /admin/abdm."""
        return {
            "code": self.code,
            "action": self.action,
            "retry": self.retry,
            "retryAt": self.retry_at,
            "what": self.what,
            "nextStep": self.next_step,
            "detail": self.detail,
            "supportReference": self.support_reference,
        }

    def summary(self) -> str:
        """1 line for a log, an admin table or a stored `error_message`."""
        parts = [self.what, self.next_step]
        if self.detail and self.detail != self.what:
            parts.append(f"ABDM said: {self.detail}")
        if self.support_reference:
            parts.append(f"REQUEST-ID {self.support_reference}")
        return " ".join(part for part in parts if part)


@dataclass(frozen=True)
class _Rule:
    action: str
    what: str = ""
    next_step: str = ""
    wait: timedelta | None = None
    renew_permission: bool = False


# --- sandbox overrides -------------------------------------------------------------------
# An entry needs observed evidence and a line in docs/findings.md. Nothing else belongs here.

OVERRIDES: dict[str, _Rule] = {
    # Docs: "New request id". Observed: a fresh REQUEST-ID is refused too, so the key is the ABHA
    # address and the HIP, and the window is about 6 minutes (findings F6).
    "ABDM-1092": _Rule(
        WAIT,
        "ABDM refused a second request for this patient so soon after the last one.",
        "Wait until the time shown, then try again.",
        wait=TOKEN_REQUEST_WINDOW,
    ),
    # Docs: "Blocked, no retry", with no scope. Observed 2026-09-17: 1 ABHA address was blocked
    # while 2 others were served in the same minutes, so the block follows the patient (E14).
    "ABDM-1027": _Rule(
        BLOCKED,
        "ABDM blocked this patient for 24 hours.",
        "Wait until the time shown, then try again.",
        wait=BLOCK_WAIT,
    ),
    # The catalogue resolves this code to "Fix request" because the reference page lists it twice.
    # The plug only ever meets the linking spelling, "This care contexts has been already linked".
    "ABDM-1056": _Rule(TREAT_AS_SUCCESS),
}

# --- plug codes --------------------------------------------------------------------------
# Failures the plug decides for itself. They never reach ABDM.

PLUG_CODES: dict[str, _Rule] = {
    "NO_ABHA": _Rule(CANNOT_PROCEED, "This patient has no ABHA address.", "Link an ABHA first."),
    "NO_RECORDS": _Rule(CANNOT_PROCEED, "This visit has no records to share yet.", "Add records, then try again."),
    "NO_FACILITY": _Rule(
        CANNOT_PROCEED, "ABDM does not recognise this facility.", "Complete the ABDM setup for this facility."
    ),
    "NO_YEAR_OF_BIRTH": _Rule(
        FIX_REQUEST, "This patient has no year of birth.", "Add the year of birth, then try again."
    ),
    "NO_ANSWER": _Rule(RETRY, "ABDM did not answer.", "Try again."),
    "NO_PERMISSION": _Rule(RETRY, "ABDM did not give permission to share for this patient.", "Try again."),
    # M3 (HIU). A repeat is a new health-information request under the same permission.
    "NO_DATA": _Rule(RETRY, "The other facility sent no records inside the time limit.", "Fetch again."),
    "CHECKSUM": _Rule(RETRY, "A record arrived damaged.", "Fetch again."),
    "DECRYPT_FAILED": _Rule(RETRY, "A record could not be decrypted.", "Fetch again."),
    "CONSENT_NOT_LIVE": _Rule(
        NEW_CONSENT, "The patient permission has ended.", "Ask the patient for a new permission."
    ),
    "NO_CALLBACK_URL": _Rule(CANNOT_PROCEED, "The ABDM callback URL is not set.", ADMIN_LINE),
}

# --- per-code desk sentences -------------------------------------------------------------
# These change the words, never the action.

MESSAGES: dict[str, tuple[str, str]] = {
    "ABDM-1035": ("ABDM does not recognise this facility.", "Complete the ABDM setup for this facility."),
    "ABDM-1025": ("ABDM does not recognise this facility.", "Complete the ABDM setup for this facility."),
    "ABDM-1013": ("ABDM refused the ABHA number of this patient.", "Check the ABHA number, then try again."),
    "ABDM-1012": ("ABDM holds no records against this ABHA address.", "Check the ABHA address of this patient."),
    "ABDM-1114": ("ABDM found no account for these details.", "Check the details, then try again."),
    "ABDM-1022": ("ABDM received too many requests.", "Wait until the time shown, then try again."),
    "ABDM-1216": ("This ABHA address is deactivated.", "Ask the patient to activate it in the ABHA app."),
    "ABDM-1308": ("This ABHA account is deactivated.", "Ask the patient to activate it in the ABHA app."),
}

# The link call says the patient permission is wrong. The plug drops it and asks for a new one.
RENEW_PERMISSION_CODES = ("ABDM-1026", "ABDM-1038", "ABDM-1063")

# --- generic advice per action ------------------------------------------------------------

ADVICE: dict[str, tuple[str, str]] = {
    FIX_REQUEST: ("ABDM refused the request.", "Check the patient details, then try again."),
    FIX_AUTH: ("ABDM refused the permission for this patient.", "Try again."),
    NEW_REQUEST_ID: ("ABDM read the request as a repeat.", "Try again."),
    NEW_CONSENT: ("The consent does not cover this request.", "Ask the patient for a new consent."),
    RETRY: ("ABDM is not answering.", "Try again in a few minutes."),
    BACK_OFF: ("ABDM received too many requests.", "Wait until the time shown, then try again."),
    CANNOT_PROCEED: ("ABDM cannot complete this request.", ADMIN_LINE),
    ASK_SUPPORT: ("ABDM refused the request and gave no reason.", SUPPORT_LINE),
    CHASE_HIP: ("The other facility is not answering.", "Try again later."),
    BLOCKED: ("ABDM blocked this request.", "Wait until the time shown, then try again."),
    WAIT: ("ABDM refused a second request so soon after the last one.", "Wait until the time shown, then try again."),
    TREAT_AS_SUCCESS: ("", ""),
    UNCLASSIFIED: ("ABDM refused the request.", SUPPORT_LINE),
}

RETRY_KIND: dict[str, str] = {
    FIX_REQUEST: NEVER,
    FIX_AUTH: NOW,
    NEW_REQUEST_ID: NOW,
    NEW_CONSENT: NEVER,
    RETRY: NOW,
    BACK_OFF: AFTER,
    CANNOT_PROCEED: NEVER,
    ASK_SUPPORT: NEVER,
    CHASE_HIP: NEVER,
    BLOCKED: AFTER,
    WAIT: AFTER,
    TREAT_AS_SUCCESS: NEVER,
    UNCLASSIFIED: NEVER,
}

DEFAULT_WAIT: dict[str, timedelta] = {BACK_OFF: BACK_OFF_WAIT, BLOCKED: BLOCK_WAIT, WAIT: TOKEN_REQUEST_WINDOW}

# --- HTTP and transport, for a failure that carries no ABDM code ---------------------------

# Observed 2026-09-17: `m2-hip-link-care-context` answers HTTP 400 with an empty body and no code
# (findings E11). A repeat cannot help, so the desk gets the reference instead (ADR-012).
HTTP_ACTIONS: tuple[tuple[int, int, str], ...] = (
    (500, 599, RETRY),
    (429, 429, BACK_OFF),
    (401, 403, FIX_AUTH),
    (404, 404, FIX_REQUEST),
    (400, 428, ASK_SUPPORT),
)


def normalize_code(value) -> str:
    """`"ABDM-1027: "` -> `"ABDM-1027"`. The docs warn that codes arrive with trailing punctuation;
    observed 2026-09-17 on an error callback. Compare codes only through this function."""
    code = str(value or "").strip().rstrip(":").strip()
    prefix, sep, rest = code.partition("-")
    return f"{prefix.upper()}{sep}{rest}" if sep else code


def action_for(code: str) -> str:
    """The action ABDM asks for, after the sandbox overrides."""
    return _rule_for(normalize_code(code), None, "").action


def _http_action(http_status: int | None) -> str:
    for low, high, action in HTTP_ACTIONS:
        if http_status is not None and low <= http_status <= high:
            return action
    return UNCLASSIFIED


# The docs give some entries as a group ("HIS-1xxx") or a range ("HIS-400 to HIS-504") instead of 1
# code. A code that is not listed by itself falls back to its group, then to its range.
_GROUP_RE = re.compile(r"^([A-Z]+-)(\d)\d{3}$")
_HTTP_CODE_RE = re.compile(r"^HTTP_(\d{3})$")
_RANGE_RE = re.compile(r"^([A-Z]+-)(\d+) to \1(\d+)$")
_RANGES = [
    (match.group(1), int(match.group(2)), int(match.group(3)), action)
    for key, action in ERROR_ACTIONS.items()
    if (match := _RANGE_RE.match(key))
]


def _catalogue_action(code: str) -> str:
    if code in ERROR_ACTIONS:
        return ERROR_ACTIONS[code]
    group = _GROUP_RE.match(code)
    if group and f"{group.group(1)}{group.group(2)}xxx" in ERROR_ACTIONS:
        return ERROR_ACTIONS[f"{group.group(1)}{group.group(2)}xxx"]
    prefix, _, number = code.partition("-")
    if number.isdigit():
        for range_prefix, low, high, action in _RANGES:
            if range_prefix == f"{prefix}-" and low <= int(number) <= high:
                return action
    return ""


def _rule_for(code: str, http_status: int | None, exception: str) -> _Rule:
    if code in OVERRIDES:
        return OVERRIDES[code]
    if code in PLUG_CODES:
        return PLUG_CODES[code]
    action = _catalogue_action(code)
    if action:
        return _Rule(action, renew_permission=code in RENEW_PERMISSION_CODES)
    if exception:
        # A timeout or a broken connection. Nothing reached ABDM, so a repeat is safe.
        return _Rule(RETRY, "The plug could not reach ABDM.", "Try again in a few minutes.")
    return _Rule(_http_action(http_status))


def classify(
    *,
    code: str = "",
    http_status: int | None = None,
    message: str = "",
    exception: str = "",
    request_id: str = "",
    since: datetime | None = None,
) -> Failure:
    """Turn 1 failure into the shape the desk, the task and the admin page all read.

    `code`        the ABDM code, a plug code, or empty.
    `http_status` the HTTP status of the answer, when there was one.
    `message`     the message ABDM sent. It is kept as `detail` for the admin page. The desk
                  always reads the plug's own sentence, which carries no ABDM jargon (ADR-011).
    `exception`   the class name of a transport failure, for example `ConnectTimeout`.
    `request_id`  the REQUEST-ID, which is the reference support asks for.
    `since`       the time the wait runs from. For `ABDM-1092` that is when the **accepted**
                  request went out, because the window runs from that one, not from the refusal.
    """
    code = normalize_code(code)
    if http_status is None:
        # `outbound.send()` stores `HTTP_400` when ABDM refuses with no code of its own. Read the
        # status back out of it, so a stored `HTTP_503` is repeated and a stored `HTTP_400` is not.
        stored = _HTTP_CODE_RE.match(code)
        if stored:
            http_status = int(stored.group(1))
    rule = _rule_for(code, http_status, exception)
    action = rule.action
    what, next_step = ADVICE.get(action, ADVICE[UNCLASSIFIED])
    if code in MESSAGES:
        what, next_step = MESSAGES[code]
    if rule.what:
        what = rule.what
    if rule.next_step:
        next_step = rule.next_step
    next_step = next_step.replace("{reference}", request_id or "none")
    if not request_id and next_step.endswith("support: none."):
        next_step = ADMIN_LINE
    retry = RETRY_KIND.get(action, NEVER)
    wait = rule.wait or DEFAULT_WAIT.get(action)
    seconds = int(wait.total_seconds()) if wait else 0
    retry_at = since + wait if (retry == AFTER and wait and since) else None
    return Failure(
        code=code,
        action=action,
        retry=retry,
        retry_after_seconds=seconds,
        retry_at=retry_at,
        what=what,
        next_step=next_step,
        detail=message.strip(),
        support_reference=request_id,
        renew_permission=rule.renew_permission or code in RENEW_PERMISSION_CODES,
    )


def no_answer(request_id: str = "", since: datetime | None = None) -> Failure:
    """A request ABDM accepted and never answered (ADR-012 D6)."""
    return classify(code="NO_ANSWER", request_id=request_id, since=since)


def answer_overdue(sent_at: datetime | None, now: datetime) -> bool:
    """True when an accepted request has waited longer than the plug is prepared to wait."""
    return bool(sent_at) and (now - sent_at) > CALLBACK_DEADLINE


def window_open(sent_at: datetime | None, now: datetime) -> bool:
    """True while a second link-token request for the same patient would be refused (F6)."""
    return bool(sent_at) and (now - sent_at) < TOKEN_REQUEST_WINDOW


def window_ends(sent_at: datetime) -> datetime:
    return sent_at + TOKEN_REQUEST_WINDOW
