"""
The plug's tables as the developer explorer browses them (ADR-018). Pure: names only, no Django.

1 spec per model in `abdm/models.py`: the columns a list shows, the columns a row detail hides by
name (secrets: tokens, an OTP hash, a private key, a photo), the columns too heavy for a browser
(a decrypted clinical bundle belongs on the ABDM Records tab, not here), and the foreign keys that
name an exchange (`AbdmOutboundRequest`) or a callback (`AbdmCallback`), which the detail follows.
`test_dev_tables.py` parses `models.py` and checks every name here against it.
"""

TABLE_SPECS = (
    {
        "name": "abha_transactions",
        "model": "AbhaTransaction",
        "module": "m1",
        "title": "ABHA transactions",
        "list_fields": ("txn_id", "kind", "abha_number", "abha_address", "is_new", "patient", "linked_at"),
        "secret_fields": ("x_token", "refresh_token"),
        "heavy_fields": (),
        "request_fields": (),
        "callback_fields": (),
        "filters": ("patient", "kind"),
    },
    {
        "name": "outbound_requests",
        "model": "AbdmOutboundRequest",
        "module": "gateway",
        "title": "Outbound requests",
        "list_fields": ("request_id", "operation_id", "status", "http_status", "error_code", "facility", "sent_at"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": (),
        "callback_fields": (),
        "filters": ("facility", "patient", "encounter", "operation_id", "status"),
    },
    {
        "name": "callbacks",
        "model": "AbdmCallback",
        "module": "gateway",
        "title": "Callbacks",
        "list_fields": ("path", "operation_id", "signature_status", "processed_status", "received_at"),
        "secret_fields": (),
        "heavy_fields": ("raw_body",),
        "request_fields": ("outbound_request",),
        "callback_fields": (),
        "filters": ("operation_id", "signature_status", "processed_status"),
    },
    {
        "name": "profile_shares",
        "model": "AbdmProfileShare",
        "module": "m1",
        "title": "Scan and Share profiles",
        "list_fields": ("hip_id", "context", "abha_address", "token_number", "status", "patient", "received_at"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": ("ack_request",),
        "callback_fields": ("callback",),
        "filters": ("facility", "patient", "status"),
    },
    {
        "name": "link_tokens",
        "model": "AbdmLinkToken",
        "module": "m2",
        "title": "Link tokens",
        "list_fields": ("patient", "facility", "abha_address", "status", "expires_at", "error_code"),
        "secret_fields": ("token",),
        "heavy_fields": (),
        "request_fields": ("request",),
        "callback_fields": (),
        "filters": ("facility", "patient", "status"),
    },
    {
        "name": "care_contexts",
        "model": "AbdmCareContext",
        "module": "m2",
        "title": "Care contexts",
        "list_fields": ("reference_number", "display", "status", "linked_via", "linked_at", "patient", "facility"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": ("link_request", "notify_request"),
        "callback_fields": (),
        "filters": ("facility", "patient", "encounter", "status"),
    },
    {
        "name": "share_items",
        "model": "AbdmShareItem",
        "module": "m2",
        "title": "Share items",
        "list_fields": ("care_context", "hi_type", "source_model", "label", "status", "attempts", "linked_at"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": ("link_request",),
        "callback_fields": (),
        "filters": ("care_context", "status", "hi_type"),
    },
    {
        "name": "link_sessions",
        "model": "AbdmLinkSession",
        "module": "m2",
        "title": "User-initiated link sessions",
        "list_fields": ("transaction_id", "abha_address", "status", "otp_attempts", "patient", "facility"),
        "secret_fields": ("otp_hash",),
        "heavy_fields": (),
        "request_fields": (),
        "callback_fields": (),
        "filters": ("facility", "patient", "status"),
    },
    {
        "name": "consents",
        "model": "AbdmConsent",
        "module": "m2",
        "title": "Consents received (HIP)",
        "list_fields": ("consent_id", "status", "hiu_id", "purpose_code", "abha_address", "date_from", "date_to"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": ("ack_request",),
        "callback_fields": ("callback",),
        "filters": ("facility", "patient", "status"),
    },
    {
        "name": "data_requests",
        "model": "AbdmDataRequest",
        "module": "m2",
        "title": "Health-information requests (HIP)",
        "list_fields": ("transaction_id", "status", "consent_artefact_id", "received_at", "deadline_at", "pushed_at"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": ("ack_request", "push_request", "notify_request"),
        "callback_fields": ("callback",),
        "filters": ("facility", "status"),
    },
    {
        "name": "consent_requests",
        "model": "AbdmConsentRequest",
        "module": "m3",
        "title": "Consent requests (HIU)",
        "list_fields": ("consent_request_id", "status", "purpose_code", "abha_address", "patient", "facility"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": ("init_request", "status_request"),
        "callback_fields": (),
        "filters": ("facility", "patient", "status"),
    },
    {
        "name": "consent_artefacts",
        "model": "AbdmConsentArtefact",
        "module": "m3",
        "title": "Consent artefacts (HIU)",
        "list_fields": ("artefact_id", "status", "hip_id", "date_from", "date_to", "data_erase_at"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": ("fetch_request",),
        "callback_fields": (),
        "filters": ("consent_request", "status"),
    },
    {
        "name": "fetch_requests",
        "model": "AbdmFetchRequest",
        "module": "m3",
        "title": "Health-information requests (HIU)",
        "list_fields": ("transaction_id", "status", "requested_at", "deadline_at", "pages_expected", "pages_received"),
        "secret_fields": ("private_key",),
        "heavy_fields": (),
        "request_fields": ("hi_request", "notify_request"),
        "callback_fields": (),
        "filters": ("artefact", "status"),
    },
    {
        "name": "fetched_records",
        "model": "AbdmFetchedRecord",
        "module": "m3",
        "title": "Fetched records (HIU)",
        "list_fields": ("title", "hi_type", "hip_id", "checksum_ok", "resource_count", "received_at", "erased_at"),
        "secret_fields": (),
        "heavy_fields": ("bundle",),
        "request_fields": (),
        "callback_fields": (),
        "filters": ("patient", "facility", "hi_type"),
    },
    {
        "name": "hpr_profiles",
        "model": "AbdmHprProfile",
        "module": "m4",
        "title": "HPR profiles",
        "list_fields": ("user", "hpr_id", "hpr_id_number", "name", "role", "source", "token_expires_at"),
        "secret_fields": ("token", "refresh_token"),
        "heavy_fields": (),
        "request_fields": (),
        "callback_fields": (),
        "filters": ("user",),
    },
    {
        "name": "hpr_logins",
        "model": "AbdmHprLogin",
        "module": "m4",
        "title": "HPR logins in progress",
        "list_fields": ("user", "hpr_id", "auth_method", "status", "attempts", "error_code"),
        "secret_fields": (),
        "heavy_fields": (),
        "request_fields": (),
        "callback_fields": (),
        "filters": ("user", "status"),
    },
    {
        "name": "hpid_transactions",
        "model": "AbdmHpidTransaction",
        "module": "m4",
        "title": "HPID creations",
        "list_fields": ("user", "txn_id", "status", "mobile_verified", "hpr_id", "error_code"),
        "secret_fields": ("photo",),
        "heavy_fields": (),
        "request_fields": ("last_request",),
        "callback_fields": (),
        "filters": ("user", "status"),
    },
)

TABLE_BY_NAME = {spec["name"]: spec for spec in TABLE_SPECS}
