# Generated by Django 6.0 on 2026-09-18 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emr", "0082_remove_encounter_encounter_class_history"),
        ("facility", "0487_facility_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbdmCallback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("path", models.CharField(max_length=256)),
                (
                    "operation_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "request_id_header",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "timestamp_header",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "hip_id_header",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("headers_json", models.JSONField(blank=True, default=dict)),
                (
                    "signature_status",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("ok", "Ok"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="missing",
                        max_length=16,
                    ),
                ),
                (
                    "signature_header",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "signature_error",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("raw_body", models.TextField(blank=True, default="")),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                (
                    "response_request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "processed_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("unhandled", "Unhandled"),
                            ("handled", "Handled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("received_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="AbdmConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("consent_id", models.CharField(max_length=128, unique=True)),
                (
                    "abha_address",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("hiu_id", models.CharField(blank=True, default="", max_length=128)),
                ("hiu_name", models.CharField(blank=True, default="", max_length=256)),
                (
                    "purpose_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("hi_types", models.JSONField(blank=True, default=list)),
                ("care_context_references", models.JSONField(blank=True, default=list)),
                ("date_from", models.DateTimeField(blank=True, null=True)),
                ("date_to", models.DateTimeField(blank=True, null=True)),
                ("data_erase_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Granted"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("artefact", models.JSONField(blank=True, default=dict)),
                ("signature", models.TextField(blank=True, default="")),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "callback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abdmcallback",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AbdmLinkSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("transaction_id", models.CharField(max_length=128, unique=True)),
                (
                    "abha_address",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("care_context_references", models.JSONField(blank=True, default=list)),
                (
                    "link_reference_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("otp_hash", models.CharField(blank=True, default="", max_length=128)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("otp_sent", "Otp Sent"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="discovered",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AbdmOutboundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("operation_id", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("request_json", models.JSONField(blank=True, default=dict)),
                ("http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_json", models.JSONField(blank=True, default=dict)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emr.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emr.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbdmLinkToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "abha_address",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("token", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emr.patient"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbdmDataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("transaction_id", models.CharField(max_length=128, unique=True)),
                (
                    "consent_artefact_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "data_push_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("date_from", models.DateTimeField(blank=True, null=True)),
                ("date_to", models.DateTimeField(blank=True, null=True)),
                ("key_material", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("acknowledged", "Acknowledged"),
                            ("transferred", "Transferred"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("deadline_at", models.DateTimeField(db_index=True)),
                ("entries", models.JSONField(blank=True, default=list)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "callback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abdmcallback",
                    ),
                ),
                (
                    "consent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abdmconsent",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facility.facility",
                    ),
                ),
                (
                    "ack_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
                (
                    "notify_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
                (
                    "push_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="abdmconsent",
            name="ack_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="abdm.abdmoutboundrequest",
            ),
        ),
        migrations.CreateModel(
            name="AbdmCareContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("reference_number", models.CharField(db_index=True, max_length=64)),
                ("display", models.CharField(max_length=256)),
                ("hi_types", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("link_requested", "Link Requested"),
                            ("linked", "Linked"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "linked_via",
                    models.CharField(
                        blank=True,
                        choices=[("hip", "Hip"), ("user", "User")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abdm_care_context",
                        to="emr.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emr.patient"
                    ),
                ),
                (
                    "link_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
                (
                    "notify_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="abdmcallback",
            name="outbound_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="abdm.abdmoutboundrequest",
            ),
        ),
        migrations.CreateModel(
            name="AbhaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "txn_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("enrol_aadhaar", "Enrol Aadhaar"),
                            ("login_mobile", "Login Mobile"),
                            ("login_abha_number", "Login Abha Number"),
                            ("login_abha_address", "Login Abha Address"),
                            ("login_aadhaar", "Login Aadhaar"),
                            ("profile_share", "Profile Share"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "abha_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "abha_address",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("is_new", models.BooleanField(null=True)),
                ("x_token", models.TextField(blank=True, default="")),
                ("x_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, default="")),
                (
                    "refresh_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("consent_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "consent_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AbdmProfileShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "hip_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("context", models.CharField(blank=True, default="", max_length=64)),
                ("hpr_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "abha_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "abha_address",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("profile", models.JSONField(blank=True, default=dict)),
                (
                    "token_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("acknowledged", "Acknowledged"),
                            ("ack_failed", "Ack Failed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(db_index=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ack_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
                (
                    "callback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abdmcallback",
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facility.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emr.patient",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abhatransaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(
                fields=["operation_id", "status"], name="abdm_abdmou_operati_d4240b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(
                fields=["facility", "status"], name="abdm_abdmou_facilit_b6c4f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(
                fields=["patient", "status"], name="abdm_abdmou_patient_82063b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(
                fields=["encounter", "status"], name="abdm_abdmou_encount_e6fbfd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="abdmlinktoken",
            constraint=models.UniqueConstraint(
                fields=("patient", "facility"), name="abdm_link_token_patient_facility"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmcarecontext",
            index=models.Index(
                fields=["patient", "status"], name="abdm_abdmca_patient_d57263_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmcarecontext",
            index=models.Index(
                fields=["facility", "status"], name="abdm_abdmca_facilit_2a9989_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="abdmcarecontext",
            constraint=models.UniqueConstraint(
                fields=("facility", "reference_number"),
                name="abdm_care_context_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(
                fields=["path", "received_at"], name="abdm_abdmca_path_f7bc60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(
                fields=["response_request_id"], name="abdm_abdmca_respons_3fca55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(
                fields=["transaction_id"], name="abdm_abdmca_transac_0d1201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(
                fields=["signature_status"], name="abdm_abdmca_signatu_a047d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abdmprofileshare",
            index=models.Index(
                fields=["facility", "received_at"],
                name="abdm_abdmpr_facilit_c65d78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abdmprofileshare",
            index=models.Index(
                fields=["facility", "context", "received_at"],
                name="abdm_abdmpr_facilit_896272_idx",
            ),
        ),
    ]
