# Generated by Django 6.0 on 2026-09-09 13:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("emr", "0082_remove_encounter_encounter_class_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbhaTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("txn_id", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("enrol_aadhaar", "Enrol Aadhaar"), ("login_mobile", "Login Mobile")], max_length=32
                    ),
                ),
                ("abha_number", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("abha_address", models.CharField(blank=True, default="", max_length=128)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("is_new", models.BooleanField(null=True)),
                ("x_token", models.TextField(blank=True, default="")),
                ("x_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, default="")),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="emr.patient"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
