# Generated by Django 6.0 on 2026-09-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abdmcallback',
            name='signature_error',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='abdmcallback',
            name='signature_header',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
