# Generated by Django 6.0 on 2026-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="abhatransaction",
            name="refresh_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="abhatransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("enrol_aadhaar", "Enrol Aadhaar"),
                    ("login_mobile", "Login Mobile"),
                    ("login_abha_number", "Login Abha Number"),
                    ("login_abha_address", "Login Abha Address"),
                    ("login_aadhaar", "Login Aadhaar"),
                ],
                max_length=32,
            ),
        ),
    ]
