# Generated by Django 6.0 on 2026-09-18 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbdmShareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('hi_type', models.CharField(choices=[('OPConsultation', 'Op Consultation'), ('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report'), ('DischargeSummary', 'Discharge Summary')], max_length=32)),
                ('source_model', models.CharField(choices=[('encounter', 'Encounter'), ('medication_request_prescription', 'Prescription'), ('diagnostic_report', 'Diagnostic Report'), ('report_upload', 'Report Upload')], max_length=48)),
                ('source_id', models.BigIntegerField()),
                ('label', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('queued', 'Queued'), ('linked', 'Linked'), ('failed', 'Failed'), ('excluded', 'Excluded')], db_index=True, default='staged', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=512)),
                ('care_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_items', to='abdm.abdmcarecontext')),
                ('link_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='abdm.abdmoutboundrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['care_context', 'status'], name='abdm_abdmsh_care_co_fa1cbc_idx'), models.Index(fields=['status', 'next_attempt_at'], name='abdm_abdmsh_status_49fe87_idx')],
                'constraints': [models.UniqueConstraint(fields=('care_context', 'hi_type', 'source_model', 'source_id'), name='abdm_share_item_source')],
            },
        ),
    ]


def keep_history(apps, schema_editor):
    """Every HI type a care context already advertised becomes 1 linked item, so the sandbox
    history stays readable on the ABDM tab (ADR-013 consequences)."""
    from django.utils import timezone

    CareContext = apps.get_model("abdm", "AbdmCareContext")
    ShareItem = apps.get_model("abdm", "AbdmShareItem")
    now = timezone.now()
    for context in CareContext.objects.exclude(hi_types=[]):
        for hi_type in context.hi_types or []:
            ShareItem.objects.get_or_create(
                care_context=context,
                source_model="encounter",
                source_id=context.encounter_id,
                hi_type=hi_type,
                defaults={
                    "label": f"{hi_type} (linked before staged sharing)",
                    "status": "linked" if context.status == "linked" else "staged",
                    "linked_at": context.linked_at if context.status == "linked" else None,
                    "link_request": context.link_request,
                    "created_date": now,
                    "modified_date": now,
                },
            )


Migration.operations.append(migrations.RunPython(keep_history, migrations.RunPython.noop))
