# Generated by Django 6.0 on 2026-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0002_abdmcallback_signature_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='abdmoutboundrequest',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
