# Generated by Django 6.0 on 2026-09-10 14:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abdm", "0002_abhatransaction_refresh_token_expires_at_and_more"),
        ("emr", "0082_remove_encounter_encounter_class_history"),
        ("facility", "0487_facility_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbdmOutboundRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("request_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("operation_id", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("succeeded", "Succeeded"), ("failed", "Failed")],
                        db_index=True,
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("request_json", models.JSONField(blank=True, default=dict)),
                ("http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_json", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=128)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="emr.encounter"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="facility.facility"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="emr.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbdmCallback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("path", models.CharField(max_length=256)),
                ("operation_id", models.CharField(blank=True, default="", max_length=128)),
                ("request_id_header", models.CharField(blank=True, default="", max_length=128)),
                ("timestamp_header", models.CharField(blank=True, default="", max_length=64)),
                ("hip_id_header", models.CharField(blank=True, default="", max_length=128)),
                ("headers_json", models.JSONField(blank=True, default=dict)),
                (
                    "signature_status",
                    models.CharField(
                        choices=[("missing", "Missing"), ("ok", "Ok"), ("failed", "Failed")],
                        db_index=True,
                        default="missing",
                        max_length=16,
                    ),
                ),
                ("raw_body", models.TextField(blank=True, default="")),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                ("response_request_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("transaction_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "shape_status",
                    models.CharField(
                        choices=[("unvalidated", "Unvalidated"), ("ok", "Ok"), ("mismatch", "Mismatch")],
                        default="unvalidated",
                        max_length=16,
                    ),
                ),
                (
                    "processed_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("unhandled", "Unhandled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("received_at", models.DateTimeField(db_index=True)),
                (
                    "outbound_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="abdm.abdmoutboundrequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(fields=["operation_id", "status"], name="abdm_abdmou_operati_d4240b_idx"),
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(fields=["facility", "status"], name="abdm_abdmou_facilit_b6c4f5_idx"),
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(fields=["patient", "status"], name="abdm_abdmou_patient_82063b_idx"),
        ),
        migrations.AddIndex(
            model_name="abdmoutboundrequest",
            index=models.Index(fields=["encounter", "status"], name="abdm_abdmou_encount_e6fbfd_idx"),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(fields=["path", "received_at"], name="abdm_abdmca_path_f7bc60_idx"),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(fields=["response_request_id"], name="abdm_abdmca_respons_3fca55_idx"),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(fields=["transaction_id"], name="abdm_abdmca_transac_0d1201_idx"),
        ),
        migrations.AddIndex(
            model_name="abdmcallback",
            index=models.Index(fields=["signature_status"], name="abdm_abdmca_signatu_a047d5_idx"),
        ),
    ]
