# Generated by Django 6.0 on 2026-09-19 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0003_hiu_consent_requests'),
        ('facility', '0487_facility_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbdmHpidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('txn_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('link_created', 'Link Created'), ('aadhaar_verified', 'Aadhaar Verified'), ('account_exists', 'Account Exists'), ('mobile_verified', 'Mobile Verified'), ('created', 'Created'), ('failed', 'Failed')], db_index=True, default='link_created', max_length=24)),
                ('aadhaar_url', models.URLField(blank=True, default='', max_length=1024)),
                ('link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('photo', models.TextField(blank=True, default='')),
                ('mobile_masked', models.CharField(blank=True, default='', max_length=32)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('existing', models.JSONField(blank=True, default=dict)),
                ('hpr_id', models.CharField(blank=True, default='', max_length=128)),
                ('hpr_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('last_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='abdm.abdmoutboundrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbdmHprLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('hpr_id', models.CharField(max_length=128)),
                ('auth_method', models.CharField(max_length=16)),
                ('txn_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('mobile_masked', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('otp_sent', 'Otp Sent'), ('verified', 'Verified'), ('failed', 'Failed')], default='otp_sent', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbdmHprProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('hpr_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('hpr_id_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('category_code', models.CharField(blank=True, default='', max_length=16)),
                ('sub_category_code', models.CharField(blank=True, default='', max_length=16)),
                ('role', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('login', 'Login'), ('created', 'Created')], default='login', max_length=16)),
                ('account', models.JSONField(blank=True, default=dict)),
                ('professional', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_method', models.CharField(blank=True, default='', max_length=16)),
                ('token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abdm_hpr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
